# Tensor Shape-Shifting & Sorcery

**Module 1 | Lesson 2**

---

## Professor Torchenstein's Grand Directive

Mwahahaha! You have summoned your first tensors from the ether! They are... raw. Untamed. Clumps of numerical clay awaiting a master's touch. A lesser mind would be content with their existence, but not you. Not us!

Today, we sculpt! We will learn the arcane arts of tensor manipulation. We will not merely *use* data; we will bend it, twist it, and reshape it to our will until it confesses its secrets. This is not data processing; this is **tensor sorcery**! Prepare to command the very dimensions of your data!

![pytorch tensors everywhere](/assets/images/torchenstein_working_computer.png)


---

## Your Mission Briefing

By the time you escape this chamber of knowledge, you will have etched the following incantations into your very soul:

*   **The Art of Selection:** Pluck elements, rows, or slices from a tensor with masterful **slicing**.
*   **Forbidden Fusions:** Combine disparate tensors into unified monstrosities with `torch.cat` and `torch.stack`.
*   **Metamorphic Mastery:** Change a tensor's very form without altering its essence using `reshape` and `view`.
*   **Dimensional Sorcery:** Add or remove dimensions at will with the mystical `squeeze` and `unsqueeze` commands.
*   **The Grand Permutation:** Reorder dimensions to your strategic advantage with `permute` and `transpose`.

**Estimated Time to Completion:** 20 minutes of exhilarating dimensional gymnastics.

**What You'll Need:**
*   The wisdom from our [last lesson on summoning tensors](../01_introduction_to_tensors.ipynb).
*   A will of iron and a mind ready to be bent!
*   Your PyTorch environment, humming with anticipation.


## Part 1: The Art of Selection - Slicing

Before you can reshape a tensor, you must learn to grasp its individual parts. Indexing is your scalpel, allowing you to perform precision surgery on your data. Slicing is your cleaver, letting you carve out whole sections for your grand experiments.

We will start by summoning a test subject—a 2D tensor brimming with potential! We must also prepare our lab with the usual incantations (`import torch` and `manual_seed`) to ensure our results are repeatable. We are scientists, not chaos-wizards!



In [2]:
import torch

# Set the seed for cosmic consistency
torch.manual_seed(42)

# Our test subject: A 2D tensor of integers. Imagine it's a map to a hidden treasure!
# Or perhaps experimental results from a daring new potion.
subject_tensor = torch.randint(0, 100, (5, 4))

print(f"Our subject tensor of shape {subject_tensor.shape}, ripe for dissection:")
print(subject_tensor)


Our subject tensor of shape torch.Size([5, 4]), ripe for dissection:
tensor([[42, 67, 76, 14],
        [26, 35, 20, 24],
        [50, 13, 78, 14],
        [10, 54, 31, 72],
        [15, 95, 67,  6]])


### Sweeping Strikes: Accessing Rows and Columns

Previous lesson: [01_introduction_to_tensors.ipynb](01_introduction_to_tensors.ipynb) gives you the basics for accessing element of a tensor.
But what if we require an entire row or column for our dark machinations? For this, we use the colon `:`, the universal symbol for "give me everything along this dimension!"

- `[row_index, :]` - Fetches the entire row.
- `[:, column_index]` - Fetches the entire column.

Let's seize the entire 3rd row (index 2) and the 2nd column (index 1).


In [3]:
# Get the entire 3rd row (index 2)
third_row = subject_tensor[2, :] # or simply subject_tensor[2]
print(f"The third row: {third_row}")
print(f"Shape of the row: {third_row.shape}\n")


# Get the entire 2nd column (index 1)
second_column = subject_tensor[:, 1]
print(f"The second column: {second_column}")
print(f"Shape of the column: {second_column.shape}")

The third row: tensor([50, 13, 78, 14])
Shape of the row: torch.Size([4])

The second column: tensor([67, 35, 13, 54, 95])
Shape of the column: torch.Size([5])


### Carving Chunks: The Power of Slicing

Mere elements are but trivialities! True power lies in carving out entire sub-regions of a tensor. Slicing uses the `start:end` notation. As with all Pythonic sorcery, the `start` is inclusive, but the `end` is **exclusive**.

Let us carve out the block containing the 2nd and 3rd rows (indices 1 and 2), and the last two columns (indices 2 and 3).


In [5]:
# Carve out rows 1 and 2, and columns 2 and 3
sub_tensor = subject_tensor[1:3, 2:4]

print("Our carved sub-tensor:")
print(sub_tensor)
print(f"Shape of the sub-tensor: {sub_tensor.shape}")


Our carved sub-tensor:
tensor([[20, 24],
        [78, 14]])
Shape of the sub-tensor: torch.Size([2, 2])


### Conditional Conjuring: Boolean Mask Indexing

Now for a truly diabolical technique! We can use a **boolean mask** to summon only the elements that meet our nefarious criteria. A boolean mask is a tensor of the same shape as our subject, but it contains only `True` or `False` values. When used for indexing, it returns a 1D tensor containing only the elements where the mask was `True`.

Let's find all the alchemical ingredients in our tensor with a value greater than 50!


In [13]:
# Create the boolean mask
mask = subject_tensor > 50

print("The boolean mask (True where value > 50):")
print(mask)

# Apply the mask
selected_elements = subject_tensor[mask]

print("\nElements greater than 50:")
print(selected_elements)
print(f"Shape of the result: {selected_elements.shape} (always a 1D tensor!)")

# You can also combine conditions! Mwahaha!
# Let's find elements between 20 and 40.
mask_combined = (subject_tensor > 20) & (subject_tensor < 40)
print("\nElements between 20 and 40:")
print(subject_tensor[mask_combined])


The boolean mask (True where value > 50):
tensor([[False,  True,  True, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False,  True, False,  True],
        [False,  True,  True, False]])

Elements greater than 50:
tensor([67, 76, 78, 54, 72, 95, 67])
Shape of the result: torch.Size([7]) (always a 1D tensor!)

Elements between 20 and 40:
tensor([26, 35, 24, 31])


### Your Mission: The Slicer's Gauntlet

Enough of my demonstrations! The scalpel is now in your hand. Prove your mastery with these challenges!

1.  **The Corner Pocket:** From our `subject_tensor`, select the element in the very last row and last column.
2.  **The Central Core:** Select the inner `3x2` block of the `subject_tensor` (that's rows 1-3 and columns 1-2).
3.  **The Even Stevens:** Create a boolean mask to select only the elements in `subject_tensor` that are even numbers. (Hint: The modulo operator `%` is your friend!)
4.  **The Grand Mutation:** Use your boolean mask from challenge 3 to **change** all even numbers in the `subject_tensor` to the value `-1`. Then, print the mutated tensor. Yes, my apprentice, indexing can be used for assignment! This is a pivotal secret!


In [ ]:
# Your code for the Slicer's Gauntlet goes here!

# --- 1. The Corner Pocket ---
print("--- 1. The Corner Pocket ---")
corner_element = subject_tensor[-1, -1] # Negative indexing for the win!
print(f"The corner element is: {corner_element.item()}\n")

# --- 2. The Central Core ---
print("--- 2. The Central Core ---")
central_core = subject_tensor[1:4, 1:3]
print(f"The central core:\\n{central_core}\n")

# --- 3. The Even Stevens ---
print("--- 3. The Even Stevens ---")
even_mask = subject_tensor % 2 == 0
print(f"The mask for even numbers:\\n{even_mask}\n")
print(f"The even numbers themselves: {subject_tensor[even_mask]}\n")


# --- 4. The Grand Mutation ---
print("--- 4. The Grand Mutation ---")
# Let's not mutate our original, that would be reckless! Let's clone it first.
mutated_tensor = subject_tensor.clone()
mutated_tensor[even_mask] = -1
print(f"The tensor after mutating even numbers to -1:\n{mutated_tensor}")


## Part 2: Forbidden Fusions - Joining Tensors

Ah, but dissecting tensors is only half the art! A true master must also know how to **fuse** separate tensors into a single, magnificent whole. Sometimes your data comes in fragments—perhaps different batches, different features, or different time steps. You must unite them!

We have two primary spells for this dark ritual:
- **`torch.cat()`** - The Concatenator! Joins tensors along an *existing* dimension.
- **`torch.stack()`** - The Stacker! Creates a *new* dimension and stacks tensors along it.

The difference is subtle but critical. Choose wrongly, and your creation will crumble! Let us forge some test subjects to demonstrate this power.


In [15]:

# Three 2x3 tensors, our loyal minions awaiting fusion
tensor_a = torch.ones(2, 3)
tensor_b = torch.ones(2, 3) * 2
tensor_c = torch.ones(2, 3) * 3

print("Our test subjects, ready for fusion:")
print(f"Tensor A (shape {tensor_a.shape}):\n{tensor_a}\n")
print(f"Tensor B (shape {tensor_b.shape}):\n{tensor_b}\n")
print(f"Tensor C (shape {tensor_c.shape}):\n{tensor_c}\n")


Our test subjects, ready for fusion:
Tensor A (shape torch.Size([2, 3])):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor B (shape torch.Size([2, 3])):
tensor([[2., 2., 2.],
        [2., 2., 2.]])

Tensor C (shape torch.Size([2, 3])):
tensor([[3., 3., 3.],
        [3., 3., 3.]])



### The Concatenator: `torch.cat()`

`torch.cat()` joins tensors along an **existing dimension**. Think of it as gluing them end-to-end. 

The key rule: *All tensors must have the same shape, except along the dimension you're concatenating!*

- `dim=0` (or `axis=0`): Concatenate along rows (vertically stack)
- `dim=1` (or `axis=1`): Concatenate along columns (horizontally join)

Let us witness this concatenation sorcery!


In [21]:
# Concatenating along dimension 0 (rows) - like stacking pancakes! 🥞⬆️⬇️
cat_dim0 = torch.cat([tensor_a, tensor_b, tensor_c], dim=0)
print("Concatenated along dimension 0 (rows) [stacking pancakes 🥞⬆️⬇️]:")
print(f"Result shape: {cat_dim0.shape}")
print(f"Result:\n{cat_dim0}\n")

# Concatenating along dimension 1 (columns) - like laying bricks side by side! 🧱🧱🧱
cat_dim1 = torch.cat([tensor_a, tensor_b, tensor_c], dim=1)
print("Concatenated along dimension 1 (columns) [laying bricks side by side 🧱🧱🧱]:")
print(f"Result shape: {cat_dim1.shape}")
print(f"Result:\n{cat_dim1}")


Concatenated along dimension 0 (rows) [stacking pancakes 🥞⬆️⬇️]:
Result shape: torch.Size([6, 3])
Result:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [3., 3., 3.],
        [3., 3., 3.]])

Concatenated along dimension 1 (columns) [laying bricks side by side 🧱🧱🧱]:
Result shape: torch.Size([2, 9])
Result:
tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
        [1., 1., 1., 2., 2., 2., 3., 3., 3.]])


### The Concatenation Rules: When Shapes Don't Match

Now, let us test the fundamental law of concatenation with unequal tensors! Remember: **All tensors must have the same shape, except along the dimension you're concatenating.**

Eg1. If you joining 2D matrices along rows (dim=0) the number of collumns should be the same. 

Let's create two tensors with different shapes and see what happens:

In [ ]:
# Create tensors with different shapes
tensor_wide = torch.ones(3, 8) * 4   # 3x5 tensor filled with 4s
tensor_narrow = torch.ones(3, 2) * 5  # 3x2 tensor filled with 5s

print(f"Wide tensor [big cake 🎂] (shape {tensor_wide.shape}):\n{tensor_wide}\n")
print(f"Narrow tensor [small cupcake 🧁 ] (shape {tensor_narrow.shape}):\n{tensor_narrow}\n")

# This FAILS: Concatenating along dimension 0, you can stack pancakes with different sizes 
# They have different column counts (5 vs 2)
print("❌ Attempting to concatenate along dimension 0 (rows), stack cake on top of cupcake ...")
try:
    cat_cols_fail = torch.cat([tensor_wide, tensor_narrow], dim=0)
except RuntimeError as e:
    print(f"🎂/🧁 This couldn't work! \nError as expected: {str(e)}")
    print("The shapes don't match along dimension 0!")

print("Our unequal test subjects:")
print(f"Wide tensor [big cake 🎂] ({tensor_wide.shape}):\n{tensor_wide}\n")
print(f"Narrow tensor [small cupcake 🧁] ({tensor_narrow.shape}):\n{tensor_narrow}\n")

# This WORKS: Concatenating along dimension 0 (rows)
# Both have 3 rows, so we can stack them vertically
print("✅ Concatenating along dimension 0 (rows) - SUCCESS!")
cat_rows_success = torch.cat([tensor_wide, tensor_narrow], dim=1)
print(f"Result shape: {cat_rows_success.shape}")
print(f"Result:\n{cat_rows_success}\n")




Wide tensor [big cake 🎂] (shape torch.Size([3, 8])):
tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])

Narrow tensor [small cupcake 🧁 ] (shape torch.Size([3, 2])):
tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])

❌ Attempting to concatenate along dimension 0 (rows), stack cake on top of cupcake ...
🎂/🧁 This couldn't work! 
Error as expected: Sizes of tensors must match except in dimension 0. Expected size 8 but got size 2 for tensor number 1 in the list....
The shapes don't match along dimension 0!
Our unequal test subjects:
Wide tensor [big cake 🎂] (torch.Size([3, 8])):
tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])

Narrow tensor [small cupcake 🧁] (torch.Size([3, 2])):
tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])

✅ Concatenating along dimension 0 (rows) - SUCCESS!
Result shape: torch.Size([3, 10])
Result:
tenso

### The Stacker: `torch.stack()`

`torch.stack()` is more dramatic! It creates an **entirely new dimension** and places each tensor along it. All input tensors must have *identical* shapes—no exceptions!

This is perfect when your tensors represent the same type of data, but from different samples, time steps, or batches.


In [ ]:
# Stacking creates a new dimension
stack_dim0 = torch.stack([tensor_a, tensor_b, tensor_c], dim=0)
print("Stacked along NEW dimension 0:")
print(f"Result shape: {stack_dim0.shape}")  # Notice the new dimension!
print(f"Result:\n{stack_dim0}\n")

# We can stack along any dimension we choose to create
stack_dim1 = torch.stack([tensor_a, tensor_b, tensor_c], dim=1)
print("Stacked along NEW dimension 1:")
print(f"Result shape: {stack_dim1.shape}")
print(f"Result:\n{stack_dim1}")


### The Fusion Dilemma: When to Cat vs. Stack?

This choice torments many apprentices! Let me illuminate the path:

**Use `torch.cat()` when:**
- Tensors represent *different parts* of the same data (e.g., different batches of images, different chunks of text)
- You want to *extend* an existing dimension
- Example: Concatenating multiple batches of training data

**Use `torch.stack()` when:**
- Tensors represent *parallel data* of the same type (e.g., predictions from different models, different time steps)  
- You need to create a *new dimension* to organize the data
- Example: Combining RGB channels to form a color image, or collecting multiple predictions

Observe this real-world scenario!


In [ ]:
# Real-world example: Building a batch of images
# Imagine these are grayscale images (height=2, width=3)
image1 = torch.randn(2, 3)  
image2 = torch.randn(2, 3)
image3 = torch.randn(2, 3)

print("Individual images:")
print(f"Image 1 shape: {image1.shape}")
print(f"Image 2 shape: {image2.shape}")  
print(f"Image 3 shape: {image3.shape}\n")

# STACK them to create a batch (batch_size=3, height=2, width=3)
image_batch = torch.stack([image1, image2, image3], dim=0)
print(f"Batch of images shape: {image_batch.shape}")
print("Perfect for feeding into a neural network!\n")

# Now imagine we have RGB channels for one image
red_channel = torch.randn(2, 3)
green_channel = torch.randn(2, 3) 
blue_channel = torch.randn(2, 3)

# STACK them to create RGB image (channels=3, height=2, width=3)
rgb_image = torch.stack([red_channel, green_channel, blue_channel], dim=0)
print(f"RGB image shape: {rgb_image.shape}")
print("The classic (C, H, W) format!")


### Your Mission: The Fusion Master's Gauntlet

The theory is yours—now prove your mastery! Complete these fusion challenges:

1. **The Triple Stack**: Create three 1D tensors of length 4 with different values. Stack them to create a 2D tensor of shape `(3, 4)`.

2. **The Horizontal Fusion**: Create two 2D tensors of shape `(3, 2)`. Concatenate them horizontally to create a `(3, 4)` tensor.

3. **The Batch Builder**: You have 5 individual "samples" (each a 1D tensor of length 3). Stack them to create a proper batch tensor of shape `(5, 3)` suitable for training.

4. **The Dimension Disaster**: Try to concatenate two tensors with different shapes: `(2, 3)` and `(2, 4)` along dimension 1. Observe the error message—it's quite educational! Then fix it by concatenating along dimension 0 instead.

5. **The Multi-Fusion**: Create a tensor of shape `(2, 6)` by first stacking three `(2, 2)` tensors, then concatenating the result with another `(3, 6)` tensor. This requires combining both operations!


In [ ]:
# Your code for the Fusion Master's Gauntlet goes here!

print("--- 1. The Triple Stack ---")
tensor1 = torch.tensor([1, 2, 3, 4])
tensor2 = torch.tensor([5, 6, 7, 8]) 
tensor3 = torch.tensor([9, 10, 11, 12])
triple_stack = torch.stack([tensor1, tensor2, tensor3], dim=0)
print(f"Triple stack result:\n{triple_stack}")
print(f"Shape: {triple_stack.shape}\n")

print("--- 2. The Horizontal Fusion ---")
left_tensor = torch.randn(3, 2)
right_tensor = torch.randn(3, 2)
horizontal_fusion = torch.cat([left_tensor, right_tensor], dim=1)
print(f"Horizontal fusion shape: {horizontal_fusion.shape}\n")

print("--- 3. The Batch Builder ---")
samples = [torch.randn(3) for _ in range(5)]  # 5 samples of length 3
batch = torch.stack(samples, dim=0)
print(f"Batch shape: {batch.shape}")
print("Ready for neural network training!\n")

print("--- 4. The Dimension Disaster ---")
disaster_a = torch.randn(2, 3)
disaster_b = torch.randn(2, 4)
try:
    # This will fail!
    bad_cat = torch.cat([disaster_a, disaster_b], dim=1)
except RuntimeError as e:
    print(f"Error (as expected): {e}")
    
# The fix: concatenate along dimension 0
good_cat = torch.cat([disaster_a, disaster_b], dim=0)  
print(f"Fixed by concatenating along dim 0: {good_cat.shape}\n")

print("--- 5. The Multi-Fusion ---")
# First, create and stack three (2,2) tensors
small_tensors = [torch.randn(2, 2) for _ in range(3)]
# Actually, let's concatenate the (2,2) tensors along dim=1 first
concat_part = torch.cat(small_tensors, dim=1)  # Shape: (2, 6)
print(f"Multi-fusion result shape: {concat_part.shape}")
print("The key was concatenating, not stacking!")
