# Summoning Your First Tensors

**Module 1 | Lesson 1**

---

### Professor Torchenstein's Grand Directive

Mwahahaha! Welcome, my brilliant acolytes. Today, we shall peel back the very fabric of reality—or, at the very least, the fabric of a PyTorch tensor. We are not merely learning; we are engaging in the sacred act of *creation*!

"Prepare your minds! The tensors... they are about to be summoned!"

---

### Your Mission Briefing

By the end of this dark ritual, you will have mastered the arcane arts of:

*   **Understanding** what a tensor is and why it's the fundamental building block of all modern AI.
*   **Summoning** tensors from nothingness using a variety of powerful PyTorch functions.
*   **Inspecting** the very soul of a tensor: its shape, data type, and the device it inhabits.

**Estimated Time to Completion:** 15 glorious minutes of pure, unadulterated learning.

**What You'll Need:**
*   A mind hungry for forbidden knowledge!
*   A working PyTorch environment, ready for spellcasting.
*   (Optional but recommended) A beverage of your choice—creation is thirsty work!

## The Grand Unveiling: What is a Tensor, *Really*?

### The Theory Behind the Magic

First, we must understand the incantation before we cast the spell. You've heard the word "tensor," whispered in the hallowed halls of academia and screamed during GPU memory overflows. But what *is* it?

Forget what the mathematicians told you about coordinate transformations for a moment. In our glorious domain of PyTorch, a tensor is simply a **multi-dimensional array of numbers**. It is the generalization of vectors and matrices to an arbitrary number of dimensions. Think of it as the ultimate container for your data!

- A **scalar** (a single number, like `5`) is a 0-dimensional tensor.
- A **vector** (a list of numbers, like `[1, 2, 3]`) is a 1-dimensional tensor.
- A **matrix** (a grid of numbers) is a 2-dimensional tensor.
- And a **tensor**? It can be all of those, and so much more! 3D, 4D, 5D... all await your command!

**Why not just use matrices?** Mwahaha, a foolish question! Modern data is complex!
- An image is not a flat grid; it's a 3D tensor (`height`, `width`, `channels`).
- A batch of images for training is a 4D tensor (`batch_size`, `height`, `width`, `channels`).
- Text data is often represented as 3D tensors (`batch_size`, `sequence_length`, `embedding_dimension`).

Tensors give us the power to mold and shape all this data with a single, unified tool. They are the clay from which we will sculpt our magnificent AI creations!

## The Ritual: Summoning Your First Tensors

Enough theory! The time has come to channel the raw power of PyTorch. We will now perform the summoning rituals—the core functions you will use constantly in your dark arts.

First, let's prepare the laboratory by importing `torch` and setting a manual seed. Why the seed? To ensure our "random" experiments are reproducible! We are scientists, not gamblers!

### 1. Conjuring from Existing Data (`torch.tensor`)

The most direct way to create a tensor is from existing data, like a Python list. The `torch.tensor()` command consumes your data and transmutes it into a glorious PyTorch tensor.

In [3]:
import torch

# Set the seed for reproducibility
torch.manual_seed(42)

# A humble Python list
my_list = [[1, 2, 3], [4, 5, 6]]

# The transmutation!
my_tensor = torch.tensor(my_list)

print(my_tensor)
print(type(my_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


### 2. Summoning Tensors of a Specific Size

Often, you won't have data yet. You simply need a tensor of a particular shape, a blank canvas for your masterpiece.

- `torch.randn(shape)`: Summons a tensor filled with random numbers from a standard normal distribution (mean 0, variance 1). Perfect for initializing weights in a neural network!
- `torch.zeros(shape)`: Creates a tensor of the given shape filled entirely with zeros.
- `torch.ones(shape)`: Creates a tensor of the given shape filled entirely with ones.

In [4]:
# A 2x3 tensor of random numbers
random_tensor = torch.randn(2, 3)
print(f"A random tensor:\n {random_tensor}\n")

# A 3x2 tensor of zeros
zeros_tensor = torch.zeros(3, 2)
print(f"A tensor of zeros:\n {zeros_tensor}\n")

# A 2x2x2 tensor of ones
ones_tensor = torch.ones(2, 2, 2)
print(f"A tensor of ones:\n {ones_tensor}")


A random tensor:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

A tensor of zeros:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

A tensor of ones:
 tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


## Inspecting Your Creation

A true master understands their creation. Once you have summoned a tensor, you must learn to inspect its very soul. These are the three most critical attributes you will constantly examine:

- `.shape`: Reveals the dimensions of your tensor. A vital sanity check!
- `.dtype`: Shows the data type of the elements within the tensor (e.g., `torch.float32`, `torch.int64`).
- `.device`: Tells you where the tensor lives—on the humble CPU or the glorious GPU.


In [ ]:
# Let's create a tensor to inspect
inspection_tensor = torch.randn(3, 4)

print(f"The tensor:\n {inspection_tensor}\n")

# Inspecting its soul
print(f"Shape of the tensor: {inspection_tensor.shape}")
print(f"Data type of the tensor: {inspection_tensor.dtype}")
print(f"Device the tensor is on: {inspection_tensor.device}")


### 3. Creating Sequential Tensors

Sometimes, you need tensors with predictable, orderly values.

- `torch.arange(start, end, step)`: Creates a 1D tensor with values from `start` (inclusive) to `end` (exclusive), with a given `step`. It's the PyTorch version of Python's `range()`.
- `torch.linspace(start, end, steps)`: Creates a 1D tensor with a specific number of `steps` evenly spaced between `start` and `end` (both inclusive).


### Your Mission: Forge Your Own Sequences!

Now it is your turn, apprentice! Put your knowledge to the test.

*   **Apprentice Challenge:** Create a 1D tensor containing all odd numbers from 1 up to (and including) 19.
*   **Artisan Challenge:** Create a 1D tensor that has 9 evenly spaced numbers between 50 and 100 (inclusive of both).

Unleash the code in the cell below! Mwahaha!


In [ ]:
# Your code for the challenges goes here!

# Apprentice Challenge Solution
odd_numbers = torch.arange(1, 20, 2)
print(f"Odd Numbers Tensor: {odd_numbers}")

# Artisan Challenge Solution
evenly_spaced = torch.linspace(50, 100, 9)
print(f"Evenly Spaced Tensor: {evenly_spaced}")

